### ISSUE TITLE
auto deployment slack bot

### ISSUE THREAD

**Issue by navilera** [planck-lang/planck#6]
I just want to make following process:
1. run 'make slackbot_deploy'
1. automatically send the Chanshik's slackbot server the files (I don't know how..) :
 * libplanck.a
 * setup.py
 * planck_module.c
 * planckbot.py

Chanshik's slackbot server have to do following:
1. Receive above files
1. Create python C-extention (planck-blah-blah.so)
1. Replace old python C-extention to the new created file
1. Re-start planck slackbot

**Comment by webispy** [comment]
@chanshik 
You can download the build artifact from Release page. (https://github.com/planck-lang/planck/releases)
